version: "3.9"
services:
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password # hasło do zmiany
      POSTGRES_USER: postgres
      POSTGRES_DB: testpostgres #hr360_database
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: dockette/adminer:pgsql
    depends_on:
      - postgres
    ports:
      - 5600:80
    # expose:
    #   - 80
    restart: unless-stopped
  
volumes:
  postgres-data: